language: python
python:
  - "3.6.8"
script:
  - fuser -k 8000/tcp
  - source /home/hans/myblog/venv/bin/activate
  - pip install -r requirements.txt
  - nohup  gunicorn --bind 0.0.0.0:8000 myblog.wsgi &
  - echo end

