# Generated by Django 2.2.6 on 2019-11-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('orderlv', models.SmallIntegerField(unique=True)),
                ('use_tf', models.BooleanField(default=True)),
                ('post_num', models.SmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'category_category',
                'ordering': ['orderlv'],
            },
        ),
    ]
