# Generated by Django 2.2.6 on 2019-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
